# Generated by Django 5.1.4 on 2025-12-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
